---
- name: Configure Web Server
  hosts: local
  become: true

  vars:
    package: apache2

  tasks:
    - name: Install apache
      ansible.builtin.package:
        name: "{{ package }}"
        state: present

      notify: Restart service

    - name: Copy website
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html
        mode: "0600"

  handlers:
    - name: Restart service
      ansible.builtin.service:
        name: "{{ package }}"
        state: started
